<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_nama toko</name>
   <tag></tag>
   <elementGuidId>7c4f1fcd-78d7-4ef1-8597-fd89d2d082ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='name-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d6699f0b-5e51-466b-93a6-ffee6ecfcb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label</value>
      <webElementGuid>71a54279-2bd5-49f7-9e12-8012f229dfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>59b0aeb0-7888-4312-bbd3-e14e437df7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-1701hoo</value>
      <webElementGuid>7511e14f-6a3e-4412-a267-062d12fde105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nama toko</value>
      <webElementGuid>e44c80f0-6e40-479e-a506-bc083721fbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label&quot;)</value>
      <webElementGuid>9cecd8c7-6d02-460c-85c8-37af9096453d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='name-label']</value>
      <webElementGuid>d3c1d831-c690-4c8a-9540-0a90e6b47518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/label</value>
      <webElementGuid>6df2e264-2ca4-4e8f-af6f-8a3c06692148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- kasirAjaDev'])[1]/following::label[1]</value>
      <webElementGuid>1701899d-b70e-402e-9962-09791a547e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hai, kasirAja'])[1]/following::label[1]</value>
      <webElementGuid>1f15019b-f968-4ae4-baf4-7afe191e7b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email'])[1]/preceding::label[1]</value>
      <webElementGuid>69f8dae5-2b2a-4557-960e-ae5a5221cf2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='password'])[1]/preceding::label[2]</value>
      <webElementGuid>1eb0c48b-8539-45dc-8abc-64e5279ca76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nama toko']/parent::*</value>
      <webElementGuid>be1b201f-4246-4778-92bb-f9c019f552f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d06dc6d6-ca52-400a-93de-3bcb41c09e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'name-label' and (text() = 'nama toko' or . = 'nama toko')]</value>
      <webElementGuid>46c471ae-e045-48f0-8fbb-adc7e26aa091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
